// Copyright (C) 2018  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 18.1 (Build Build 625 09/12/2018)
// Created on Mon Nov 19 11:55:56 2018

VGA_controller VGA_controller_inst
(
	.clk(clk_sig) ,	// input  clk_sig
	.write_zone(write_zone_sig) ,	// output  write_zone_sig
	.count1(count1_sig) ,	// output [9:0] count1_sig
	.count2(count2_sig) ,	// output [9:0] count2_sig
	.h_sync(h_sync_sig) ,	// output  h_sync_sig
	.v_sync(v_sync_sig) 	// output  v_sync_sig
);

defparam VGA_controller_inst.horizontal_resolution = 640;
defparam VGA_controller_inst.vertical_resolution = 480;
defparam VGA_controller_inst.start_horizontal_write = 97;
defparam VGA_controller_inst.finish_horizontal_write = 544;
defparam VGA_controller_inst.start_vertical_write = 206;
defparam VGA_controller_inst.finish_vertical_write = 275;
